const stylelintConfig = {
  extends: ["stylelint-config-standard"],
  plugins: ["stylelint-declaration-strict-value"],
  ignoreFiles: [".next/**", "coverage/**", "playwright-report/**", "test-results/**"],
  rules: {
    "custom-property-pattern": null,
    "selector-class-pattern": null,
    "declaration-property-value-disallowed-list": {
      transition: ["/\\ball\\b/"],
    },
    "scale-unlimited/declaration-strict-value": [
      [
        "/color$/",
        "background",
        "background-color",
        "background-image",
        "border",
        "border-block",
        "border-block-end",
        "border-block-start",
        "border-color",
        "border-inline",
        "border-inline-end",
        "border-inline-start",
        "border-radius",
        "border-start-start-radius",
        "border-start-end-radius",
        "border-end-start-radius",
        "border-end-end-radius",
        "border-width",
        "box-shadow",
        "text-shadow",
        "font",
        "font-family",
        "font-size",
        "font-weight",
        "letter-spacing",
        "line-height",
        "z-index",
        "transition",
        "transition-delay",
        "transition-duration",
        "transition-timing-function",
        "animation",
        "animation-delay",
        "animation-duration",
        "animation-timing-function",
        "width",
        "min-width",
        "max-width",
        "height",
        "min-height",
        "max-height",
        "inline-size",
        "min-inline-size",
        "max-inline-size",
        "block-size",
        "min-block-size",
        "max-block-size",
        "aspect-ratio",
        "flex-basis",
        "outline",
        "outline-offset",
        "outline-width",
        "filter",
        "transform",
        "gap",
        "column-gap",
        "row-gap",
        "margin",
        "margin-block",
        "margin-block-end",
        "margin-block-start",
        "margin-inline",
        "margin-inline-end",
        "margin-inline-start",
        "margin-top",
        "margin-right",
        "margin-bottom",
        "margin-left",
        "padding",
        "padding-block",
        "padding-block-end",
        "padding-block-start",
        "padding-inline",
        "padding-inline-end",
        "padding-inline-start",
        "padding-top",
        "padding-right",
        "padding-bottom",
        "padding-left",
        "inset",
        "inset-block",
        "inset-block-end",
        "inset-block-start",
        "inset-inline",
        "inset-inline-end",
        "inset-inline-start",
        "top",
        "right",
        "bottom",
        "left",
      ],
      {
        ignoreValues: [
          "0",
          "1px",
          "auto",
          "currentColor",
          "inherit",
          "none",
          "fit-content",
          "solid",
          "transparent",
          "CanvasText",
          "100%",
          "0s",
        ],
        disableFix: true,
      },
    ],
  },
  overrides: [
    {
      files: ["styles/tokens.css"],
      rules: {
        "custom-property-empty-line-before": null,
        "scale-unlimited/declaration-strict-value": null,
      },
    },
  ],
};

export default stylelintConfig;
